name: Run Automated Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Build Application
        run: go build -v ./...

      - name: Run Automated Tests
        run: GIN_MODE=release go test -v ./... -tags="unit integration" ./...